sudo: required

services:
  - docker

before_install:
  - docker image build -t chouffe/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker container run chouffe/react-test npm test -- --coverage

after_success:
  # Build images
  - docker image build -t chouffe/multi-client -f ./client/Dockerfile ./client
  - docker image build -t chouffe/multi-nginx -f ./nginx/Dockerfile ./nginx
  - docker image build -t chouffe/multi-server -f ./server/Dockerfile ./server
  - docker image build -t chouffe/multi-worker -f ./worker/Dockerfile ./worker
  # Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Pushing images to Docker
  - docker image push chouffe/multi-client
  - docker image push chouffe/multi-nginx
  - docker image push chouffe/multi-server
  - docker image push chouffe/multi-worker
